---
- hosts: localhost
  connection: local

  tasks:
    - name: Build Docker image from Dockerfiles.
      docker_image:
        name: test
        source: build
        build:
          path: test
        state: present

    - name: Ensure the test container is running.
      docker_container:
        image: test:latest
        name: test
        state: started 
